mutation CreateTask($title: String!, $description: String!, $dueDate: Date, $isCompleted: Boolean!) @auth(level: USER) {
  task_insert(data: {
    title: $title,
    description: $description,
    dueDate: $dueDate,
    isCompleted: $isCompleted,
    userId_expr: "auth.uid"
  })
}

query GetTasks @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  tasks(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    title
    description
    dueDate
    isCompleted
  }
}

mutation UpdateTask($id: UUID!, $isCompleted: Boolean) @auth(level: USER) {
  task_update(
    id: $id,
    data: {
      isCompleted: $isCompleted
    }
  )
}

mutation DeleteTask($id: UUID!) @auth(level: USER) {
  task_delete(id: $id)
}